### PR TITLE
fixed bug when uploading directly

### PR DESCRIPTION
**Pull request by bagger**
Uploading files less than 5MB when no s3 key exists causing the following error:

> Traceback (most recent call last):
>  File "/usr/local/sbin/s3-mp-upload.py", line 155, in <module>
>    main(**arg_dict)
>  File "/usr/local/sbin/s3-mp-upload.py", line 102, in main
>    key.set_contents_from_file(src)
> AttributeError: 'NoneType' object has no attribute 'set_contents_from_file'

This commit fixes it.

### CODE REVIEW

**Comment by mumrah** [comment]
@bagger do you mind fixing the indentation? In the diff it looks a little funky. 4 spaces per indentation level (no tabs)

**Comment by mumrah** [comment]
Sorry, didn't mean to click "Close"

**Comment by bagger** [comment]
Yes, please :-) I've almost never write anything using Python before.

**Comment by mumrah** [comment]
@bagger don't think I can modify the pull request - you'll need to make the modification I believe. I think if you make the modification to your fork then reissue the pull request, it will append the commit to this one.

**Comment by bagger** [comment]
Ok, no problem. I'll fix it.

**Pull request merged**
